// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2AsFWd0yjMpneAp5bat7SPgaPjG-sy4k',
    appId: '1:7006486065:web:2c8183abf378adefc89f10',
    messagingSenderId: '7006486065',
    projectId: 'instagram-clone-5e54f',
    authDomain: 'instagram-clone-5e54f.firebaseapp.com',
    storageBucket: 'instagram-clone-5e54f.appspot.com',
    measurementId: 'G-4ZZGFMWPNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGfIADJylr3V4FPKK5ABpZNIk72rxf2I',
    appId: '1:7006486065:android:fb19cdb48ecc0077c89f10',
    messagingSenderId: '7006486065',
    projectId: 'instagram-clone-5e54f',
    storageBucket: 'instagram-clone-5e54f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKeffo28n8sl4m4a6GR7s1hzX2EKvLmdU',
    appId: '1:7006486065:ios:d7c751e0ad7a4b77c89f10',
    messagingSenderId: '7006486065',
    projectId: 'instagram-clone-5e54f',
    storageBucket: 'instagram-clone-5e54f.appspot.com',
    iosClientId: '7006486065-q4eck2gn9j4ai1nu1372rnfc115oc3rh.apps.googleusercontent.com',
    iosBundleId: 'com.fouadbahari.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKeffo28n8sl4m4a6GR7s1hzX2EKvLmdU',
    appId: '1:7006486065:ios:d7c751e0ad7a4b77c89f10',
    messagingSenderId: '7006486065',
    projectId: 'instagram-clone-5e54f',
    storageBucket: 'instagram-clone-5e54f.appspot.com',
    iosClientId: '7006486065-q4eck2gn9j4ai1nu1372rnfc115oc3rh.apps.googleusercontent.com',
    iosBundleId: 'com.fouadbahari.instagramClone',
  );
}
